openapi: 3.0.0
info:
  title: Komodo DeFi Framework - Lightning API
  version: v2
  description: OpenAPI specification for the lightning methods.
paths:
  /lightning::payments:
    post:
      summary: 'Komodo DeFi Framework Method Overview: Lightning Network Payments'
      description: This document provides an overview of all Lightning Network payment
        methods available in the Komodo DeFi Framework.
      operationId: lightning::payments
      tags:
      - lightning
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
              - userpass
              - method
              properties:
                userpass:
                  type: string
                  description: User password for authentication.
                  example: RPC_UserP@SSW0RD
                method:
                  type: string
                  description: Name of the method to be called.
                  enum:
                  - lightning::payments
      responses:
        '200':
          description: Successful response for lightning::payments
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/lightning_payments_Response'
              example:
                mmrpc: '2.0'
                result: {}
                id: 0
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /lightning::activation:
    post:
      summary: Lightning Network Initialization Tasks Overview
      description: Overview of Lightning Network initialization task-managed methods
        in the Komodo DeFi Framework API.
      operationId: lightning::activation
      tags:
      - lightning
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
              - userpass
              - method
              properties:
                userpass:
                  type: string
                  description: User password for authentication.
                  example: RPC_UserP@SSW0RD
                method:
                  type: string
                  description: Name of the method to be called.
                  enum:
                  - lightning::activation
      responses:
        '200':
          description: Successful response for lightning::activation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/lightning_activation_Response'
              example:
                mmrpc: '2.0'
                result: {}
                id: 0
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /lightning::nodes:
    post:
      summary: 'Komodo DeFi Framework Method Overview: Lightning Network Nodes'
      description: This document provides an overview of all Lightning Network node
        management methods available in the Komodo DeFi Framework.
      operationId: lightning::nodes
      tags:
      - lightning
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
              - userpass
              - method
              properties:
                userpass:
                  type: string
                  description: User password for authentication.
                  example: RPC_UserP@SSW0RD
                method:
                  type: string
                  description: Name of the method to be called.
                  enum:
                  - lightning::nodes
      responses:
        '200':
          description: Successful response for lightning::nodes
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/lightning_nodes_Response'
              example:
                mmrpc: '2.0'
                result: {}
                id: 0
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /lightning::channels:
    post:
      summary: 'Komodo DeFi Framework Method Overview: Lightning Network Channels'
      description: This document provides an overview of all Lightning Network channel
        management methods available in the Komodo DeFi Framework.
      operationId: lightning::channels
      tags:
      - lightning
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
              - userpass
              - method
              properties:
                userpass:
                  type: string
                  description: User password for authentication.
                  example: RPC_UserP@SSW0RD
                method:
                  type: string
                  description: Name of the method to be called.
                  enum:
                  - lightning::channels
      responses:
        '200':
          description: Successful response for lightning::channels
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/lightning_channels_Response'
              example:
                mmrpc: '2.0'
                result: {}
                id: 0
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /lightning::payments::get_payment_details:
    post:
      summary: Get Lightning Payment Details
      description: Get details of a Lightning Network payment using the Komodo DeFi
        Framework API.
      operationId: lightning::payments::get_payment_details
      tags:
      - lightning
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
              - userpass
              - method
              properties:
                userpass:
                  type: string
                  description: User password for authentication.
                  example: RPC_UserP@SSW0RD
                method:
                  type: string
                  description: Name of the method to be called.
                  enum:
                  - lightning::payments::get_payment_details
      responses:
        '200':
          description: Successful response for lightning::payments::get_payment_details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/lightning_payments_get_payment_details_Response'
              example:
                mmrpc: '2.0'
                result:
                  payment_details: {}
                  id: {}
                id: 0
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /lightning::payments::send_payment:
    post:
      summary: Send Lightning Payment
      description: Send a Lightning Network payment using the Komodo DeFi Framework
        API.
      operationId: lightning::payments::send_payment
      tags:
      - lightning
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
              - userpass
              - method
              properties:
                userpass:
                  type: string
                  description: User password for authentication.
                  example: RPC_UserP@SSW0RD
                method:
                  type: string
                  description: Name of the method to be called.
                  enum:
                  - lightning::payments::send_payment
      responses:
        '200':
          description: Successful response for lightning::payments::send_payment
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/lightning_payments_send_payment_Response'
              example:
                mmrpc: '2.0'
                result:
                  payment_hash: string_value
                  status: string_value
                  id: {}
                id: 0
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /lightning::payments::list_payments_by_filter:
    post:
      summary: List Lightning Payments by Filter
      description: Returns a list of Lightning Network payments filtered by the provided
        filter object.
      operationId: lightning::payments::list_payments_by_filter
      tags:
      - lightning
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
              - userpass
              - method
              properties:
                userpass:
                  type: string
                  description: User password for authentication.
                  example: RPC_UserP@SSW0RD
                method:
                  type: string
                  description: Name of the method to be called.
                  enum:
                  - lightning::payments::list_payments_by_filter
      responses:
        '200':
          description: Successful response for lightning::payments::list_payments_by_filter
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/lightning_payments_list_payments_by_filter_Response'
              example:
                mmrpc: '2.0'
                result:
                  result: {}
                  id: {}
                id: 0
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /lightning::payments::generate_invoice:
    post:
      summary: Generate Lightning Invoice
      description: Generate a Lightning Network invoice using the Komodo DeFi Framework
        API.
      operationId: lightning::payments::generate_invoice
      tags:
      - lightning
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
              - userpass
              - method
              properties:
                userpass:
                  type: string
                  description: User password for authentication.
                  example: RPC_UserP@SSW0RD
                method:
                  type: string
                  description: Name of the method to be called.
                  enum:
                  - lightning::payments::generate_invoice
      responses:
        '200':
          description: Successful response for lightning::payments::generate_invoice
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/lightning_payments_generate_invoice_Response'
              example:
                mmrpc: '2.0'
                result:
                  invoice: string_value
                  id: {}
                id: 0
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /lightning::nodes::connect_to_node:
    post:
      summary: Connect to Lightning Node
      description: Connect to a Lightning node using the Komodo DeFi Framework API.
      operationId: lightning::nodes::connect_to_node
      tags:
      - lightning
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
              - userpass
              - method
              properties:
                userpass:
                  type: string
                  description: User password for authentication.
                  example: RPC_UserP@SSW0RD
                method:
                  type: string
                  description: Name of the method to be called.
                  enum:
                  - lightning::nodes::connect_to_node
      responses:
        '200':
          description: Successful response for lightning::nodes::connect_to_node
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/lightning_nodes_connect_to_node_Response'
              example:
                mmrpc: '2.0'
                result:
                  result: string_value
                  id: {}
                id: 0
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /lightning::nodes::remove_trusted_node:
    post:
      summary: Remove Trusted Lightning Node
      description: Remove a trusted Lightning node using the Komodo DeFi Framework
        API.
      operationId: lightning::nodes::remove_trusted_node
      tags:
      - lightning
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
              - userpass
              - method
              properties:
                userpass:
                  type: string
                  description: User password for authentication.
                  example: RPC_UserP@SSW0RD
                method:
                  type: string
                  description: Name of the method to be called.
                  enum:
                  - lightning::nodes::remove_trusted_node
      responses:
        '200':
          description: Successful response for lightning::nodes::remove_trusted_node
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/lightning_nodes_remove_trusted_node_Response'
              example:
                mmrpc: '2.0'
                result:
                  removed_node: string_value
                  id: {}
                id: 0
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /lightning::nodes::list_trusted_nodes:
    post:
      summary: List Trusted Lightning Nodes
      description: List all trusted Lightning nodes using the Komodo DeFi Framework
        API.
      operationId: lightning::nodes::list_trusted_nodes
      tags:
      - lightning
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
              - userpass
              - method
              properties:
                userpass:
                  type: string
                  description: User password for authentication.
                  example: RPC_UserP@SSW0RD
                method:
                  type: string
                  description: Name of the method to be called.
                  enum:
                  - lightning::nodes::list_trusted_nodes
      responses:
        '200':
          description: Successful response for lightning::nodes::list_trusted_nodes
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/lightning_nodes_list_trusted_nodes_Response'
              example:
                mmrpc: '2.0'
                result:
                  trusted_nodes: string_value
                  id: {}
                id: 0
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /lightning::nodes::add_trusted_node:
    post:
      summary: Add Trusted Lightning Node
      description: Add a trusted Lightning node using the Komodo DeFi Framework API.
      operationId: lightning::nodes::add_trusted_node
      tags:
      - lightning
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
              - userpass
              - method
              properties:
                userpass:
                  type: string
                  description: User password for authentication.
                  example: RPC_UserP@SSW0RD
                method:
                  type: string
                  description: Name of the method to be called.
                  enum:
                  - lightning::nodes::add_trusted_node
      responses:
        '200':
          description: Successful response for lightning::nodes::add_trusted_node
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/lightning_nodes_add_trusted_node_Response'
              example:
                mmrpc: '2.0'
                result:
                  added_node: string_value
                  id: {}
                id: 0
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /lightning::channels::close_channel:
    post:
      summary: Close Lightning Channel
      description: Close a Lightning Network channel using the Komodo DeFi Framework
        API.
      operationId: lightning::channels::close_channel
      tags:
      - lightning
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
              - userpass
              - method
              properties:
                userpass:
                  type: string
                  description: User password for authentication.
                  example: RPC_UserP@SSW0RD
                method:
                  type: string
                  description: Name of the method to be called.
                  enum:
                  - lightning::channels::close_channel
      responses:
        '200':
          description: Successful response for lightning::channels::close_channel
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/lightning_channels_close_channel_Response'
              example:
                mmrpc: '2.0'
                result:
                  status: string_value
                  id: {}
                id: 0
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /lightning::channels::get_claimable_balances:
    post:
      summary: Get Claimable Lightning Balances
      description: Get claimable Lightning Network channel balances using the Komodo
        DeFi Framework API.
      operationId: lightning::channels::get_claimable_balances
      tags:
      - lightning
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
              - userpass
              - method
              properties:
                userpass:
                  type: string
                  description: User password for authentication.
                  example: RPC_UserP@SSW0RD
                method:
                  type: string
                  description: Name of the method to be called.
                  enum:
                  - lightning::channels::get_claimable_balances
      responses:
        '200':
          description: Successful response for lightning::channels::get_claimable_balances
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/lightning_channels_get_claimable_balances_Response'
              example:
                mmrpc: '2.0'
                result:
                  result: {}
                  id: {}
                id: 0
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /lightning::channels::get_channel_details:
    post:
      summary: Get Lightning Channel Details
      description: Get details about a Lightning Network channel using the Komodo
        DeFi Framework API.
      operationId: lightning::channels::get_channel_details
      tags:
      - lightning
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
              - userpass
              - method
              properties:
                userpass:
                  type: string
                  description: User password for authentication.
                  example: RPC_UserP@SSW0RD
                method:
                  type: string
                  description: Name of the method to be called.
                  enum:
                  - lightning::channels::get_channel_details
      responses:
        '200':
          description: Successful response for lightning::channels::get_channel_details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/lightning_channels_get_channel_details_Response'
              example:
                mmrpc: '2.0'
                result:
                  status: string_value
                  details: {}
                  id: {}
                id: 0
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /lightning::channels::list_closed_channels_by_filter:
    post:
      summary: List Closed Lightning Channels by Filter
      description: List closed Lightning Network channels by filter using the Komodo
        DeFi Framework API.
      operationId: lightning::channels::list_closed_channels_by_filter
      tags:
      - lightning
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
              - userpass
              - method
              properties:
                userpass:
                  type: string
                  description: User password for authentication.
                  example: RPC_UserP@SSW0RD
                method:
                  type: string
                  description: Name of the method to be called.
                  enum:
                  - lightning::channels::list_closed_channels_by_filter
      responses:
        '200':
          description: Successful response for lightning::channels::list_closed_channels_by_filter
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/lightning_channels_list_closed_channels_by_filter_Response'
              example:
                mmrpc: '2.0'
                result:
                  result: {}
                  id: {}
                id: 0
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /lightning::channels::update_channel:
    post:
      summary: Update Lightning Channel
      description: Update a Lightning Network channel using the Komodo DeFi Framework
        API.
      operationId: lightning::channels::update_channel
      tags:
      - lightning
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
              - userpass
              - method
              properties:
                userpass:
                  type: string
                  description: User password for authentication.
                  example: RPC_UserP@SSW0RD
                method:
                  type: string
                  description: Name of the method to be called.
                  enum:
                  - lightning::channels::update_channel
      responses:
        '200':
          description: Successful response for lightning::channels::update_channel
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/lightning_channels_update_channel_Response'
              example:
                mmrpc: '2.0'
                result:
                  channel_options: {}
                  id: {}
                id: 0
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /lightning::channels::list_open_channels_by_filter:
    post:
      summary: List Open Lightning Channels by Filter
      description: List open Lightning Network channels by filter using the Komodo
        DeFi Framework API.
      operationId: lightning::channels::list_open_channels_by_filter
      tags:
      - lightning
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
              - userpass
              - method
              properties:
                userpass:
                  type: string
                  description: User password for authentication.
                  example: RPC_UserP@SSW0RD
                method:
                  type: string
                  description: Name of the method to be called.
                  enum:
                  - lightning::channels::list_open_channels_by_filter
      responses:
        '200':
          description: Successful response for lightning::channels::list_open_channels_by_filter
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/lightning_channels_list_open_channels_by_filter_Response'
              example:
                mmrpc: '2.0'
                result:
                  result: {}
                  id: {}
                id: 0
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /lightning::channels::open_channel:
    post:
      summary: Open Lightning Channel
      description: Open a new Lightning Network channel using the Komodo DeFi Framework
        API.
      operationId: lightning::channels::open_channel
      tags:
      - lightning
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
              - userpass
              - method
              properties:
                userpass:
                  type: string
                  description: User password for authentication.
                  example: RPC_UserP@SSW0RD
                method:
                  type: string
                  description: Name of the method to be called.
                  enum:
                  - lightning::channels::open_channel
      responses:
        '200':
          description: Successful response for lightning::channels::open_channel
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/lightning_channels_open_channel_Response'
              example:
                mmrpc: '2.0'
                result:
                  uuid: string_value
                  node_address: string_value
                  id: {}
                id: 0
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
components:
  schemas:
    ErrorResponse:
      type: object
      properties:
        error:
          type: string
        error_path:
          type: string
        error_trace:
          type: string
        error_type:
          type: string
        error_data:
          type: object
